# Generated by Django 3.2.23 on 2023-11-14 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voetbalspelers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the football player', max_length=200)),
                ('current_club', models.CharField(help_text='Current football club', max_length=200)),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date of entry')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='Date of last modification')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
